INSERT INTO Artist(name) VALUES ('Dianna Mcfarland');
INSERT INTO Artist(name) VALUES ('Basil Owens');
INSERT INTO Artist(name) VALUES ('Garrett Compton');
INSERT INTO Artist(name) VALUES ('Jonathan Rhodes');
INSERT INTO Artist(name) VALUES ('Jean Russo');
INSERT INTO Artist(name) VALUES ('Electroclub');

INSERT INTO Genre(name) VALUES ('Rock');
INSERT INTO Genre(name) VALUES ('Pop');
INSERT INTO Genre(name) VALUES ('Jazz');
INSERT INTO Genre(name) VALUES ('Hip-hop');
INSERT INTO Genre(name) VALUES ('Electronic');

INSERT INTO ArtistGenre(artist_id, genre_id) VALUES (1, 2);
INSERT INTO ArtistGenre(artist_id, genre_id) VALUES (2, 4);
INSERT INTO ArtistGenre(artist_id, genre_id) VALUES (3, 1);
INSERT INTO ArtistGenre(artist_id, genre_id) VALUES (4, 3);
INSERT INTO ArtistGenre(artist_id, genre_id) VALUES (5, 5);
INSERT INTO ArtistGenre(artist_id, genre_id) VALUES (6, 5);

INSERT INTO Album(name, release_year) VALUES ('Wrong', 1980);
INSERT INTO Album(name, release_year) VALUES ('Trial', 1982);
INSERT INTO Album(name, release_year) VALUES ('Chance', 1991);
INSERT INTO Album(name, release_year) VALUES ('Strap', 2000);
INSERT INTO Album(name, release_year) VALUES ('Pumpkin', 2011);
INSERT INTO Album(name, release_year) VALUES ('Sellshock', 2019);
INSERT INTO Album(name, release_year) VALUES ('Clinic', 2020);
INSERT INTO Album(name, release_year) VALUES ('Hacker', 2023);
INSERT INTO Album(name, release_year) VALUES ('Silence', 2005);
INSERT INTO Album(name, release_year) VALUES ('Techno Clock', 2016);

INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (1, 2);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (2, 3);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (3, 1);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (4, 4);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (5, 5);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (6, 6);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (5, 7);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (6, 8);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (6, 2);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (6, 9);
INSERT INTO ArtistAlbum(artist_id, album_id) VALUES (6, 10);

INSERT INTO Track(name, duration, album_id) VALUES ('A Hundred and Ten Percent', 312, 1);
INSERT INTO Track(name, duration, album_id) VALUES ('I Smell a Rat', 255, 1);
INSERT INTO Track(name, duration, album_id) VALUES ('Jaws of Life', 258, 2);
INSERT INTO Track(name, duration, album_id) VALUES ('What Am I, Chopped Liver?', 294, 2);
INSERT INTO Track(name, duration, album_id) VALUES ('A Cat Nap', 301, 3);
INSERT INTO Track(name, duration, album_id) VALUES ('A Cut Above', 219, 3);
INSERT INTO Track(name, duration, album_id) VALUES ('A Busy Body', 284, 4);
INSERT INTO Track(name, duration, album_id) VALUES ('A Bite at the Cherry', 356, 4);
INSERT INTO Track(name, duration, album_id) VALUES ('Beating Around the Bush', 228, 5);
INSERT INTO Track(name, duration, album_id) VALUES ('Long In The Tooth', 285, 5);
INSERT INTO Track(name, duration, album_id) VALUES ('Eat My Hat', 278, 6);
INSERT INTO Track(name, duration, album_id) VALUES ('Ugly Duckling', 215, 6);
INSERT INTO Track(name, duration, album_id) VALUES ('Beat myself', 267, 6);
INSERT INTO Track(name, duration, album_id) VALUES ('My cat said meow', 278, 6);
INSERT INTO Track(name, duration, album_id) VALUES ('Locked my', 230, 6);
INSERT INTO Track(name, duration, album_id) VALUES ('Put a Sock In It', 287, 7);
INSERT INTO Track(name, duration, album_id) VALUES ('Knock Your Socks Off', 258, 7);
INSERT INTO Track(name, duration, album_id) VALUES ('Break The Ice', 209, 8);
INSERT INTO Track(name, duration, album_id) VALUES ('Shot In the Dark', 318, 8);
INSERT INTO Track(name, duration, album_id) VALUES ('I dont care', 220, 9);
INSERT INTO Track(name, duration, album_id) VALUES ('Diversion', 267, 10);

INSERT INTO Collection(name, release_year) VALUES ('Close But No Cigar', 1990);
INSERT INTO Collection(name, release_year) VALUES ('On the Same Page', 2005);
INSERT INTO Collection(name, release_year) VALUES ('My Cup of Tea', 2002);
INSERT INTO Collection(name, release_year) VALUES ('No Ifs, Ands, or Buts', 2005);
INSERT INTO Collection(name, release_year) VALUES ('Beating a Dead Horse', 2011);
INSERT INTO Collection(name, release_year) VALUES ('Let Her Rip', 2018);
INSERT INTO Collection(name, release_year) VALUES ('Up In Arms', 2021);

INSERT INTO CollectionTrack(collection_id, track_id) VALUES (1, 2);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (1, 4);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (1, 6);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (2, 2);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (2, 4);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (2, 7);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (3, 5);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (3, 6);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (3, 8);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (4, 7);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (4, 8);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (4, 10);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (5, 9);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (5, 10);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (5, 1);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (6, 4);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (6, 9);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (6, 11);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (6, 12);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (6, 13);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (6, 14);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (6, 15);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (7, 16);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (7, 17);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (7, 18);
INSERT INTO CollectionTrack(collection_id, track_id) VALUES (7, 19);